base_model:
  pretrained_model_name: "runwayml/stable-diffusion-v1-5"

out_directories:
  output_dir: "out/controlnet"
  images_logs_dir: "out/logs/controlnet/generated_images"
  loss_logs_dir: "out/logs/controlnet/loss_plots"
  weights_logs_dir: "out/logs/controlnet/weights"

datasets_dirs:
  train_images_dir: "data/bubbles/bubbles_split/train/images"
  train_masks_dir: "data/bubbles/bubbles_split/train/masks"
  val_images_dir: "data/bubbles/bubbles_split/valid/images"
  val_masks_dir: "data/bubbles/bubbles_split/valid/masks"

train_params:
  num_epochs: 2
  learning_rate: 2e-5
  batch_size: 1
  image_size: 224
  log_images_step: 100
  log_loss_step: 100
  log_weights_step: 100

hardware:
  device: "mps"
  precision: "bf16"
