base_model:
  pretrained_model_name: "runwayml/stable-diffusion-v1-5"

out_directories:
  output_dir: "out/sd"
  images_logs_dir: "out/logs/sd/generated_images"
  loss_logs_dir: "out/logs/sd/loss_plots"
  weights_logs_dir: "out/logs/sd/weights"

datasets_dirs:
  train_images_dir: "data/bubbles/bubbles_split/train/images"
  val_images_dir: "data/bubbles/bubbles_split/valid/images"

train_params:
  num_epochs: 2
  learning_rate: 1e-4
  batch_size: 2
  image_size: 224
  log_images_step: 50
  log_loss_step: 100
  log_weights_step: 100

hardware:
  device: "mps"
  precision: "bf16"
